version: '3.8'
services:
  app:
    container_name: nodejs-app
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:password@db:5432/mydb
    depends_on:
      - db
    command: npx nodemon index.js

  db:
    container_name: postgres-db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=drivers-solution
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root123
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
    - 5050:80

volumes:
  postgres-data:
